services:
  - type: web
    name: whatsapp-auto-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
    disk:
      name: sessions-storage
      mountPath: /opt/render/project/src/sessions
      sizeGB: 1
